//
// Copyright © 2003-2012, by YaPB Development Team. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// Resource.hpp
//
// Description: Some important information about this project.
//
// Version: $ID:$
//

#if defined COMPILER_VISUALC && COMPILER_VISUALC > 1000
#	pragma once
#endif	// if defined COMPILER_VISUALC && COMPILER_VISUALC > 1000

#ifndef RESOURCE_INCLUDED
#define RESOURCE_INCLUDED

/// @note FROM "Core tool library/Definitions.hpp"
///@{
#define EXPAND_CALL(function, arguments) function arguments
#define STRINGIZE(text) #text	// "ptr = STRINGIZE(some text);" Equal to: "ptr = "some text";"
#define STRINGIZE_EXPAND(text) EXPAND_CALL (STRINGIZE, (text))
///@}

// General product information....
#define PRODUCT_BUILD_DWORD			3394	// Generated by build update tool (../tool/buildup/Release/buildup.exe) -- DO NOT EDIT --
#define PRODUCT_BUILD				STRINGIZE_EXPAND (PRODUCT_BUILD_DWORD)
#define PRODUCT_INTERNAL_NAME		"Ping of Death Bot"
#define PRODUCT_NAME				"Yet another " PRODUCT_INTERNAL_NAME
#define PRODUCT_SHORT_NAME			"YaPB"
#define PRODUCT_VERSION				"3.0.0." PRODUCT_BUILD " ALPHA"
#define PRODUCT_AUTHOR				PRODUCT_SHORT_NAME " Dev Team & Immortal*BLG"
#define PRODUCT_URL					"http://YaPB.Bots-United.com/"
#define PRODUCT_EMAIL				"jeefo@inbox.ru"
#define PRODUCT_LOG_TAG				PRODUCT_SHORT_NAME
#define PRODUCT_CONSOLE_TAG			"YB"
#define PRODUCT_CONSOLE_TAG_OTHER	PRODUCT_SHORT_NAME
#define PRODUCT_DESCRIPTION			PRODUCT_NAME " v" PRODUCT_VERSION " - The Counter-Strike v1.x Bot"
#define PRODUCT_COPYRIGHT_YEAR		"2003-2012"
#define PRODUCT_COPYRIGHT			"Copyright © " PRODUCT_COPYRIGHT_YEAR ", by " PRODUCT_AUTHOR ". All rights reserved."
#define PRODUCT_LEGAL				"Half-Life, Counter-Strike, Counter-Strike: Condition Zero, Steam, Valve is a trademark of Valve Corporation"
#define PRODUCT_ORIGINAL_FILENAME	PRODUCT_SHORT_NAME ".DLL"
#define PRODUCT_VERSION_DWORD		3,0,0,PRODUCT_BUILD_DWORD	// major version, minor version, WIP (or Update) version, BUILD number (generated with RES file)
#define PRODUCT_SUPPORT_VERSION		"1.6 - CZ"
#define PRODUCT_DATE				__DATE__
#define PRODUCT_TIME				__TIME__
#define PRODUCT_COMMENTS			PRODUCT_URL

// define product optimization type (we're not using CRT builds anymore)
#if defined _DEBUG
#	if defined _AFXDLL
#		define PRODUCT_OPTIMIZATION_TYPE	"Debug Build (CRT)"
#	else
#		define PRODUCT_OPTIMIZATION_TYPE	"Debug Build"
#	endif	// if defined _AFXDLL
#elif defined NDEBUG
#	if defined _AFXDLL
#		define PRODUCT_OPTIMIZATION_TYPE	"Optimized Build (CRT)"
#	else
#		define PRODUCT_OPTIMIZATION_TYPE	"Optimized Build"
#	endif	// if defined _AFXDLL
#else
#	define PRODUCT_OPTIMIZATION_TYPE		"Default Release"
#endif	// if defined _DEBUG

#endif	// ifndef RESOURCE_INCLUDED
